management:
  security:
    enabled: false
security:
  basic:
    enabled: false
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
    question-service:
      path: /question/**
      serviceId: question-service
      
      
hystrix: 
  streamEnabled: true
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
ribbon: 
  eureka: 
    enabled: true
  ServerListRefreshInterval: 1
