management:
  security:
    enabled: false
security:
  basic:
    enabled: false

zuul:
  routes:
    users:
      path: /user11/**
      serviceId: user-service
      
hystrix: 
  streamEnabled: true
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
ribbon: 
  eureka: 
    enabled: true
  ServerListRefreshInterval: 1
