zuul:
  routes:
    userService:
      path: /user/**
      service-id: user-service
    questionService:
      path: /question/**
      service-id: question-service
      
      
hystrix: 
  streamEnabled: true
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
ribbon: 
  eureka: 
    enabled: true
  ServerListRefreshInterval: 1
