
server:
  port: 9082
  
spring:
  application:
    name: gateway    
  cloud:
    config:
      uri:  http://localhost:8800
    server:
      git:
        clone-on-start=true
          
eureka: 
  instance:
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://localhost:9090/eureka/

zuul:
  routes:
    userService:
      path: /user/**
      service-id: userService
    questionService:
      path: /question/**
      service-id: questionService
      
      
hystrix: 
  streamEnabled: true
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
ribbon: 
  eureka: 
    enabled: true
  ServerListRefreshInterval: 1
