server:
  port: 9092
 
spring:
  application:
    name: userService
  cloud: 
    config: 
      uri: http://localhost:8800
    server: 
      git: 
        clone-on-start: true

userService: 
  getUser: 
    url: 
      mapping: /
      
eureka: 
  instance: 
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://localhost:9090/eureka/
